<h1>Lesson 1. kNN on Iris dataset</h1>

<table>
  <tr>
    <td><img src="https://upload.wikimedia.org/wikipedia/commons/thumb/5/56/Kosaciec_szczecinkowaty_Iris_setosa.jpg/180px-Kosaciec_szczecinkowaty_Iris_setosa.jpg" style="width:250px; height:200px;"></td>
    <td><img src="https://www.math.umd.edu/~petersd/666/html/iris_with_labels.jpg" width="250px"></td>
    <td><img src="https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Iris_virginica.jpg/295px-Iris_virginica.jpg" width="250px"></td>
  </tr>
</table>
  
  <p>This exercise relates to the <a href="https://en.wikipedia.org/wiki/Iris_flower_data_set">iris data set</a>,
which contains the morphologic variation of Iris flowers of three related species (Iris setosa, Iris virginica and Iris versicolor).</p>
<p>Four features were measured from each observation (see image above):</p>
<ul>
<li>Sepal.Length - sepal length in centimeters</li>
<li>Sepal.Width - sepal width in centimeters</li>
<li>Petal.Length - petal length in centimeters</li>
<li>Petal.Width - petal width in centimeters</li>
<li>Species - species of the flower (our outcome variable)</li>
</ul>
<p>scikit-learn comes with a few small standard datasets that do not require to download any file from some external website.</p>
<p>You can check the documentation <a href="http://scikit-learn.org/stable/datasets/index.html">here</a></p>
<p>This dataset is built in under variable 'iris'. Let's see how it looks:</p>

In [1]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris

iris = load_iris()
iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

<h3>Q.0.1 Print the object type of iris</h3>

In [3]:
# Put the command (or commands) here that would give the answer to the above question.
type(iris)

sklearn.utils.Bunch

In [4]:
print(list(iris.target_names))

['setosa', 'versicolor', 'virginica']


<h3>Q.0.2 What do the iris.target_names represent</h3>

In [5]:
# Describe what the iris.target_names represent
target names are the group of species in which we need to classify the given data

SyntaxError: invalid syntax (<ipython-input-5-8b9d47351772>, line 2)

In [5]:
print(list(iris.feature_names))

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


<h3>Q.0.3 What do the iris.feature_names represent</h3>

In [6]:
# Describe what the iris.feature_names represent
the features of the flowers which are observed

In [2]:
# print the integers representing the species of each observation
print (iris.target)
data = pd.DataFrame(iris.data)
data.columns = iris.feature_names
data['label'] = iris.target
data.head()

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   label  
0      0  
1      0  
2      0  
3      0  
4      0

<h3>Q.1. How many observations are present for each species?</h3>

In [8]:
# Put the command (or commands) here that would give an answer to the above question.
data.groupby("label").count()

# 50 observations per species

sepal length (cm)  sepal width (cm)  petal length (cm)  \
label                                                           
0                     50                50                 50   
1                     50                50                 50   
2                     50                50                 50   

       petal width (cm)  
label                    
0                    50  
1                    50  
2                    50

<h3>Q.2. Plot the Sepal.Width vs. Sepal.Length, Petal.Width vs. Petal.Length, while color-coding the species.</h3> 

In [9]:
# Write the two plot commands here
# create a scatter plot of PETAL LENGTH versus PETAL WIDTH and color by SPECIES
# create a custom colormap
import matplotlib.pyplot as plt
from matplotlib.colors import ListedColormap
cmap_bold = ListedColormap(['#FF0000', '#00FF00', '#0000FF'])

plt.scatter(data['petal length (cm)'], data['petal width (cm)'], c=data['label'],s=200,cmap=cmap_bold)


# create a scatter plot of SEPAL LENGTH versus SEPAL WIDTH and color by SPECIES
plt.scatter(data['sepal length (cm)'], data['sepal width (cm)'], c=data['label'],s=200,cmap=cmap_bold)

plt.show()

<Figure size 640x480 with 1 Axes>

<h3>Q.3. Which of the plots allows for easier determination of the flower type?</h3>

In [10]:
# Identify the plot that clearly separates the classes
Petal length vs Petal width gives an easier determination of the flower type

<br>
<p>After the initial exploratory data analysis.</p>

<h3>Q.4. Write the command to split the data into 70% train and 30% test, to prepare for k-NN modelling:</h3>

In [4]:
from sklearn.model_selection import train_test_split

# first split the dataset into its attributes and labels
# X = data.iloc[:, :-1].values 

# only take Petal.width, petal.Length as features.
X = data.iloc[:, 2:4].values  
y = data.iloc[:, 4].values  

#X_train, X_test, y_train, y_test = #TODO
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1)
X

array([[1.4, 0.2],
       [1.4, 0.2],
       [1.3, 0.2],
       [1.5, 0.2],
       [1.4, 0.2],
       [1.7, 0.4],
       [1.4, 0.3],
       [1.5, 0.2],
       [1.4, 0.2],
       [1.5, 0.1],
       [1.5, 0.2],
       [1.6, 0.2],
       [1.4, 0.1],
       [1.1, 0.1],
       [1.2, 0.2],
       [1.5, 0.4],
       [1.3, 0.4],
       [1.4, 0.3],
       [1.7, 0.3],
       [1.5, 0.3],
       [1.7, 0.2],
       [1.5, 0.4],
       [1. , 0.2],
       [1.7, 0.5],
       [1.9, 0.2],
       [1.6, 0.2],
       [1.6, 0.4],
       [1.5, 0.2],
       [1.4, 0.2],
       [1.6, 0.2],
       [1.6, 0.2],
       [1.5, 0.4],
       [1.5, 0.1],
       [1.4, 0.2],
       [1.5, 0.2],
       [1.2, 0.2],
       [1.3, 0.2],
       [1.4, 0.1],
       [1.3, 0.2],
       [1.5, 0.2],
       [1.3, 0.3],
       [1.3, 0.3],
       [1.3, 0.2],
       [1.6, 0.6],
       [1.9, 0.4],
       [1.4, 0.3],
       [1.6, 0.2],
       [1.4, 0.2],
       [1.5, 0.2],
       [1.4, 0.2],
       [4.7, 1.4],
       [4.5, 1.5],
       [4.9,

<h3>Q.5. Write the Python command that performs k-NN fit using Petal.Width and Petal.Length only using 2 neighbors.</h3>

In [5]:
from sklearn.neighbors import KNeighborsClassifier

# Instantiate learning model (k = 2)
clf = KNeighborsClassifier(n_neighbors = 2)

# Fitting the model
clf.fit(X_train,y_train)

# Predicting the Test set results
y_pred = clf.predict(X_test)
y_pred

array([0, 1, 1, 0, 2, 1, 2, 0, 0, 2, 1, 0, 2, 1, 1, 0, 1, 1, 0, 0, 1, 1,
       1, 0, 2, 1, 0, 0, 1, 2, 1, 2, 1, 2, 2, 0, 1, 0, 1, 2, 2, 0, 1, 2,
       1])

<h3>Q.6. Evaluate your algorithm using the confusion_matrix and classification_report methods of the sklearn.metrics</h3>

In [6]:
from sklearn.metrics import classification_report, confusion_matrix  
from sklearn.metrics import confusion_matrix
from sklearn import metrics

print(confusion_matrix(y_test, y_pred))  
print(classification_report(y_test, y_pred))
print(metrics.accuracy_score(y_test, y_pred))

[[14  0  0]
 [ 0 18  0]
 [ 0  1 12]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        14
           1       0.95      1.00      0.97        18
           2       1.00      0.92      0.96        13

    accuracy                           0.98        45
   macro avg       0.98      0.97      0.98        45
weighted avg       0.98      0.98      0.98        45

0.9777777777777777


<h3>Q.7. What accuracy did you obtain?</h3>

In [13]:
.9777

0.9777

<h3>Q.8. Try with different values of k (3 and 5), do you observe any difference in your result? Explain.</h3>

In [ ]:
getting accuracy 0.9555555555555556

<h3>Q.9. List three methods that can be used to improve prediction quality</h3>

In [ ]:
# 1. Choosing the most applicable set of variables
As we could see from plotting in the scatter plot, petal length and petal width combination are very good features to base the classification.
We could see when we take those two features, the different species could be spotted easily.
Smaller petal length and petal width meant it was Sentosa species, and largest petal length and petal width meant it was Viginica species.
So chosing most applicable set of variables is important.

# 2. Choosing an optimal value for k for kNN
Trying with different values of K to check which suits the most helps.

# 3. Not overfitting the data in general
K-NN performs better with a lower number of features than a large number of features. 
We can say that when the number of features increases, then it requires more data. 
Increase in dimension also leads to the problem of overfitting. 
To avoid overfitting, the needed data will need to grow exponentially as we increase the number of dimensions.
This problem of higher dimension is known as the Curse of Dimensionality.

<h3>Q.10. Create a new text cell in your Notebook: Complete a 50-100 word summary 
    (or short description of your thinking in applying this week's learning to the solution) 
     of your experience in this assignment. Include:
<br>                                                                       
What was your incoming experience with this model, if any?
what steps you took, what obstacles you encountered.
how you link this exercise to real-world, machine learning problem-solving. (What steps were missing? What else do you need to learn?)
This summary allows your instructor to know how you are doing and allot points for your effort in thinking and planning, and making connections to real-world work.
</h3>

In [ ]:
# Add your response here

KNN classification is one of the most easiest and fastest way to classify data. 
Performing the scatter plot taking the feature sets explained what should be the features based on which if we try to classify, we would get the best result.
Also interesting was the chosing value of K.
It looked like, because "petal lenghth" and "petal width" are such good feature set to easily classify the species, when we chose lower value of K, we got very good accuracy.

When we are increasing the value of K, the classification accuracy decreased. It was because we were taking in a bigger set of neighbours to be classified upon.

We had used KNN in our Office work project, where we had to find the nearest answer to asked question. We had a repository of questions and answers, and provided a question, we had to find, if we had a "Similar" question and answer set.

I think I need to learn how various distance measures such as Euclidean distance, Hamming distance, Manhattan distance, and Minkowski distance effect the performance of KNN classification.

